# http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html
# http://www.gnu.org/software/bash/manual/bashref.html
# how to override an alias?

alias ls='ls -la'
alias faction='ssh psbehr@psbehr.webfactional.com'
alias 'git-purge'='git rm $(git ls-files --deleted)'

export PS1="\[\e[0;33m\]\h:\w \\$ \[\e[0m\]"
export CLICOLOR=1
export LSCOLORS=gxfxcxdxcxeggdcbcgacad
export TERM=xterm-color

if [ -e ~/.bashrc_extra ]; then
    . ~/.bashrc_extra
fi

if [ -e ~/Documents/code/active/ ]; then
    cd ~/Documents/code/active/
fi
