# http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html
# http://www.gnu.org/software/bash/manual/bashref.html
# how to override an alias?

alias ls='ls -la'
alias faction='ssh psbehr@psbehr.webfactional.com'
alias cc=gcc

export PS1="\h:\w \\$ "
export CLICOLOR=1
export LSCOLORS=gxfxcxdxcxeggdcbcgacad
export TERM=xterm-color

cd ~/Documents/code/active/

# OS X specific on Nova 

export PATH=/opt/local/bin:/opt/local/sbin:$PATH
export PATH=/Library/Frameworks/UnixImageIO.framework/Programs:$PATH
export PATH=/Library/Frameworks/PROJ.framework/Programs:$PATH
export PATH=/Library/Frameworks/GEOS.framework/Programs:$PATH
export PATH=/Library/Frameworks/SQLite3.framework/Programs:$PATH
export PATH=/Library/Frameworks/GDAL.framework/Programs:$PATH
export PATH=/usr/local/node/bin:$PATH
export PATH=/usr/local/mysql/bin:$PATH
#PATH=$PATH:/usr/local/teTeX/bin/powerpc-apple-darwin-current
