# http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html
# http://www.gnu.org/software/bash/manual/bashref.html
# how to override an alias?

alias ls='ls -la'
alias faction='ssh psbehr@psbehr.webfactional.com'

export PS1="\[\e[0;33m\]\h:\w \\$ \[\e[0m\]"
export CLICOLOR=1
export LSCOLORS=gxfxcxdxcxeggdcbcgacad
export TERM=xterm-color

if [ -e ~/.bashrc_extra ]; then
    . ~/.bashrc_extra
fi

if [ -e ~/Documents/code/active/ ]; then
    cd ~/Documents/code/active/
fi

# OS X specific on Nova 

export PATH=/opt/local/bin:/opt/local/sbin:$PATH
export PATH=/Library/Frameworks/UnixImageIO.framework/Programs:$PATH
export PATH=/Library/Frameworks/PROJ.framework/Programs:$PATH
export PATH=/Library/Frameworks/GEOS.framework/Programs:$PATH
export PATH=/Library/Frameworks/SQLite3.framework/Programs:$PATH
export PATH=/Library/Frameworks/GDAL.framework/Programs:$PATH
export PATH=/usr/local/node/bin:$PATH
export PATH=/usr/local/mysql/bin:$PATH
#PATH=$PATH:/usr/local/teTeX/bin/powerpc-apple-darwin-current
