""" Peter Behr's .vimrc, whoo

" http://www.oualline.com/vim-cook.html
" http://vim.wikia.com/wiki/Vim_Tips_Wiki
" whitespace rules?
" http://vimdoc.sourceforge.net

""" Pathogen

filetype off
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

""" syntax

set background=dark
syntax on

""" display

set nu " line numbers
set ruler " want scrollbar position
set listchars=tab:▸\ ,eol:¬ " invisibles
set list
"set textwidth=80 " want soft rewrap
" want alternating four space columns on background

""" indentation

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set ai

""" encoding

set encoding=utf-8

""" other

set mouse=a
set directory=/tmp,/var/tmp,.

" key mappings

noremap <silent> <C-n> :NERDTreeToggle<CR>
noremap <silent> <C-h> :bp<CR>
noremap <silent> <C-l> :bn<CR>
" copying, this is broken
vnoremap <silent> <C-c> :!pbcopy<CR>
" need pasting and cutting, obviously
" quitting, this also has problems
noremap <silent> <C-q> :qall<CR>
noremap <silent> <C-w> :q<CR>
noremap <silent> <C-o> <C-w>w
"noremap <silent> <Esc>
"noremap <silent> :qall
" save as

" mapping for qall
" including modules?
" mapping for moving between nerdtree and elsewhere
" nerdtree width


""" start commands

autocmd VimEnter * NERDTree
autocmd VimEnter * wincmd l
